// Content model for theCareLineMD — ported verbatim from the original design source.
// Do not paraphrase copy here; these strings are the site's marketing content.

export interface Feature { title: string; desc: string }
export interface FAQ { q: string; a: string }
export interface Metric { value: string; label: string }

export interface Service {
  slug: string; name: string; initials: string; path: string; tagline: string;
  h1: string; intro: string; features: Feature[]; hasMetrics: boolean;
  metrics: Metric[]; faq: FAQ[];
}
export interface Software {
  slug: string; name: string; initials: string; path: string; tagline: string;
  h1: string; intro: string; mockup: string; features: Feature[]; faq: FAQ[];
}
export interface Industry {
  slug: string; name: string; path: string; summary: string;
  challenges: string[]; solutions: string[];
}
export interface Resource {
  slug: string; title: string; category: string; excerpt: string;
  relatedSlugs: { services?: string[]; software?: string[] }; body: string[];
}

export const SERVICES: Service[] = [
  {slug:'medical-billing', name:'Medical Billing', initials:'MB', path:'/services/medical-billing', tagline:'Full-service billing and coding for clean, fast-paying claims.', h1:'Medical billing services built around your revenue', intro:'End-to-end billing operations — charge entry, coding, claim submission, and payment posting — run by a dedicated healthcare billing team.', features:[{title:'Charge entry & coding',desc:'Accurate CPT/ICD-10 coding reviewed before every claim goes out.'},{title:'Claims submission',desc:'Professional and institutional claims filed daily, scrubbed for errors.'},{title:'Payment posting',desc:'Remittances posted and reconciled against expected reimbursement.'}], hasMetrics:true, metrics:[{value:'98.4%',label:'Average clean claim rate'},{value:'28 days',label:'Average days in AR'}], faq:[{q:'How quickly can you take over billing?',a:'Most practices are fully transitioned within 30-45 days, including data migration and payer credentialing checks.'},{q:'Do you work with our existing PMS/EHR?',a:'Yes — our team integrates with most major practice management and EHR systems, or you can move to our own PMS.'}]},
  {slug:'medical-coding', name:'Medical Coding', initials:'MC', path:'/services/medical-coding', tagline:'Certified coders reviewing every claim for accuracy and compliance.', h1:'Certified medical coding that protects your revenue', intro:'Reduce coding-related denials with certified coders who review documentation against payer-specific rules before submission.', features:[{title:'CPT/HCPCS & ICD-10 coding',desc:'Specialty-specific coding aligned to current guidelines.'},{title:'Documentation review',desc:'Flags for under-documentation before claims go out the door.'},{title:'Coding audits',desc:'Periodic audits to catch drift and training opportunities.'}], hasMetrics:false, metrics:[], faq:[{q:'Are your coders certified?',a:'Coding is performed by staff holding recognized coding certifications with specialty-specific experience.'},{q:'Can you audit our current coding?',a:'Yes, we offer a coding audit as part of onboarding or as a standalone engagement.'}]},
  {slug:'claims-processing', name:'Claims Processing', initials:'CP', path:'/services/claims-processing', tagline:'Professional and institutional claims, scrubbed and tracked to resolution.', h1:'Claims processing that gets you paid on the first pass', intro:'From clearinghouse submission to payer follow-up, we manage professional and institutional claims end to end.', features:[{title:'Professional claims (CMS-1500)',desc:'Physician and outpatient claims prepared and submitted daily.'},{title:'Institutional claims (UB-04)',desc:'Facility claims handled with attention to billing rules and modifiers.'},{title:'Claim scrubbing',desc:'Automated and manual checks before submission to cut first-pass denials.'}], hasMetrics:true, metrics:[{value:'98.4%',label:'First-pass acceptance rate'},{value:'<48 hrs',label:'Average submission turnaround'}], faq:[{q:'What clearinghouse do you use?',a:'We work through established clearinghouse partners and can align with your existing setup if preferred.'},{q:'Do you handle both professional and institutional claims?',a:'Yes, our team supports both CMS-1500 and UB-04 claim types across specialties.'}]},
  {slug:'payment-posting', name:'Payment Posting', initials:'PP', path:'/services/payment-posting', tagline:'ERA/EOB posting and reconciliation with daily accuracy checks.', h1:'Payment posting that keeps your books accurate', intro:'Every remittance — electronic or paper — is posted, reconciled, and flagged for variance within one business day.', features:[{title:'ERA & EOB posting',desc:'Electronic and manual remittances posted with variance checks.'},{title:'Contractual adjustments',desc:'Write-offs applied per payer contract terms.'},{title:'Underpayment flagging',desc:'Payments below expected allowables routed for appeal review.'}], hasMetrics:false, metrics:[], faq:[{q:'How fast is posting turned around?',a:'Remittances are typically posted within one business day of receipt.'},{q:'What happens if a payment looks wrong?',a:'Underpayments and denials found during posting are routed directly into our denial management workflow.'}]},
  {slug:'denial-management', name:'Denial Management', initials:'DM', path:'/services/denial-management', tagline:'Root-cause tracking and appeals to recover revenue that stalls.', h1:'Denial management that recovers revenue and stops repeat denials', intro:'We track every denial to its root cause, file timely appeals, and feed findings back into your billing workflow to prevent recurrence.', features:[{title:'Denial triage',desc:'Every denial categorized by reason code and routed to the right resolution path.'},{title:'Appeals filing',desc:'Clinical and administrative appeals prepared and tracked to resolution.'},{title:'Trend reporting',desc:'Root-cause reporting so recurring denial patterns get fixed upstream.'}], hasMetrics:true, metrics:[{value:'32%*',label:'Avg. denial rate reduction'},{value:'4.1%',label:'Typical denial rate after 6 months'}], faq:[{q:'How do you decide which denials to appeal?',a:'We evaluate every denial for appeal viability based on payer policy, documentation, and recoverable value.'},{q:'Do you handle IDR for out-of-network claims?',a:'Yes — see our IDR & Appeals Management service for No Surprises Act-related disputes.'}]},
  {slug:'idr-appeals-management', name:'IDR & Appeals Management', initials:'IDR', path:'/services/idr-appeals-management', tagline:'Independent Dispute Resolution and appeals for out-of-network claims.', h1:'IDR and appeals management for complex disputes', intro:'We manage the Independent Dispute Resolution process and complex payer appeals so out-of-network and underpaid claims don\'t go uncollected.', features:[{title:'IDR case preparation',desc:'Documentation and offer preparation for federal and state IDR processes.'},{title:'Appeals escalation',desc:'Multi-level appeals for claims stuck at first-level denial.'},{title:'Case tracking',desc:'Full visibility into every dispute\'s stage and expected timeline.'}], hasMetrics:false, metrics:[], faq:[{q:'Do you handle No Surprises Act disputes?',a:'Yes, our team supports the federal IDR process for eligible out-of-network claims.'},{q:'How long does IDR typically take?',a:'Timelines vary by case and payer responsiveness; we track and report on every open dispute.'}]},
  {slug:'ar-management', name:'AR Management', initials:'AR', path:'/services/ar-management', tagline:'Aging accounts worked systematically until resolved or written off.', h1:'AR management that keeps balances from going stale', intro:'We work your aging AR on a defined cadence — following up with payers and patients until every balance is resolved.', features:[{title:'Aging bucket workflows',desc:'Accounts worked by age and dollar value with defined follow-up cadences.'},{title:'Payer follow-up',desc:'Outbound calls and portal checks on unpaid or pending claims.'},{title:'AR reporting',desc:'Weekly visibility into aging trends and recovery progress.'}], hasMetrics:true, metrics:[{value:'28 days',label:'Average days in AR'},{value:'9 days*',label:'Typical AR reduction'}], faq:[{q:'How old of AR can you take on?',a:'We work both current and legacy aged AR, including backlogs from prior billing vendors.'},{q:'Do you contact patients directly?',a:'Yes, patient balance follow-up is included as part of our AR workflow, handled respectfully and per your policies.'}]},
  {slug:'eligibility-verification', name:'Eligibility & Prior Authorization', initials:'EV', path:'/services/eligibility-verification', tagline:'Insurance verification and prior auth handled before the visit.', h1:'Eligibility verification & prior authorization before the patient arrives', intro:'We confirm coverage and secure prior authorizations ahead of each visit, reducing front-desk surprises and avoidable denials.', features:[{title:'Real-time eligibility checks',desc:'Coverage and benefits confirmed before appointments.'},{title:'Prior authorization',desc:'Auth requests submitted and tracked through payer turnaround.'},{title:'Patient responsibility estimates',desc:'Estimated copay/coinsurance shared ahead of the visit.'}], hasMetrics:true, metrics:[{value:'<24 hrs*',label:'Average verification turnaround'},{value:'32%*',label:'Reduction in eligibility-related denials'}], faq:[{q:'How far in advance do you verify eligibility?',a:'Typically 24-72 hours before scheduled appointments, depending on payer response times.'},{q:'Can this integrate with our scheduling system?',a:'Yes, eligibility checks can run against your existing schedule or our PMS.'}]},
  {slug:'credentialing', name:'Healthcare Credentialing', initials:'CR', path:'/services/credentialing', tagline:'Payer enrollment and re-credentialing managed end to end.', h1:'Healthcare credentialing without the paperwork burden', intro:'We manage payer enrollment, re-credentialing, and CAQH upkeep so providers can bill and get paid without administrative delays.', features:[{title:'Payer enrollment',desc:'New provider applications prepared and tracked to completion.'},{title:'Re-credentialing',desc:'Ongoing re-attestation and renewal tracking to avoid lapses.'},{title:'CAQH maintenance',desc:'Profile upkeep to keep applications moving smoothly.'}], hasMetrics:false, metrics:[], faq:[{q:'How long does credentialing take?',a:'Timelines vary by payer, typically 60-120 days; we track every application and provide status updates.'},{q:'Do you handle group and individual enrollment?',a:'Yes, we support both individual provider and group-level payer enrollment.'}]},
  {slug:'revenue-cycle-management', name:'Revenue Cycle Management', initials:'RCM', path:'/services/revenue-cycle-management', tagline:'The full billing lifecycle, managed as one connected system.', h1:'Revenue cycle management as one connected system', intro:'From eligibility to final resolution, we manage the entire revenue cycle as a single accountable process — not a set of disconnected vendors.', features:[{title:'End-to-end ownership',desc:'One team accountable for eligibility through final collection.'},{title:'Analytics & reporting',desc:'Practice-level dashboards on collections, denials, and AR trends.'},{title:'Continuous improvement',desc:'Monthly reviews to tighten workflows and reduce leakage.'}], hasMetrics:true, metrics:[{value:'98.4%',label:'Clean claim rate'},{value:'32%*',label:'Avg. denial rate reduction'}], faq:[{q:'Is this different from just outsourcing billing?',a:'RCM covers the full lifecycle — eligibility, coding, claims, posting, denials, and AR — as one managed process rather than piecemeal tasks.'},{q:'Can we start with one part of RCM and expand?',a:'Yes, many clients begin with billing or denial management and expand scope over time.'}]},
];
export const SOFTWARE: Software[] = [
  {slug:'ehr', name:'EHR', initials:'EHR', path:'/software/ehr', tagline:'Electronic health records built for fast, accurate documentation.', h1:'An EHR built for fast, accurate clinical documentation', intro:'Chart visits, manage problem lists, and route orders — all connected to billing so documentation supports clean claims from the start.', mockup:'ehr', features:[{title:'Specialty-aware templates',desc:'Note templates tuned to common specialty workflows.'},{title:'Orders & e-prescribing',desc:'Labs, referrals, and prescriptions from within the chart.'},{title:'Billing-connected charting',desc:'Documentation flows directly into coding and claims.'}], faq:[{q:'Can we migrate data from our current EHR?',a:'Yes, our team supports data migration planning as part of implementation.'},{q:'Does the EHR connect to your billing service?',a:'Yes — it\'s built to hand off cleanly to our billing and RCM workflows, or to your existing billing vendor.'}]},
  {slug:'pms', name:'PMS', initials:'PMS', path:'/software/pms', tagline:'Scheduling, registration, and front-office operations in one place.', h1:'Practice management software for a smoother front office', intro:'Scheduling, patient registration, and eligibility checks in one system — built to reduce no-shows and front-desk friction.', mockup:'pms', features:[{title:'Smart scheduling',desc:'Multi-provider, multi-location scheduling with automated reminders.'},{title:'Patient registration',desc:'Digital intake forms that sync directly to the chart.'},{title:'Eligibility at check-in',desc:'Coverage checks run automatically ahead of each visit.'}], faq:[{q:'Does the PMS work standalone?',a:'Yes, PMS can run independently or alongside our EHR and billing services.'},{q:'Can it handle multiple locations?',a:'Yes, multi-location and multi-provider scheduling is supported out of the box.'}]},
  {slug:'patient-portal', name:'Patient Portal', initials:'PP', path:'/software/patient-portal', tagline:'Appointments, messaging, and bill pay patients actually use.', h1:'A patient portal built for real adoption', intro:'Appointment requests, secure messaging, and online bill pay in a simple interface designed to cut down front-desk call volume.', mockup:'portal', features:[{title:'Appointment requests',desc:'Patients request and confirm visits without calling in.'},{title:'Secure messaging',desc:'HIPAA-aware messaging between patients and care teams.'},{title:'Online bill pay',desc:'Patients view balances and pay directly from the portal.'}], faq:[{q:'How do patients access the portal?',a:'Via web or a mobile-friendly interface, with credentials issued at registration.'},{q:'Does bill pay connect to our billing system?',a:'Yes, payments post directly against the patient balance in real time.'}]},
  {slug:'healthcare-crm', name:'Healthcare CRM', initials:'CRM', path:'/software/healthcare-crm', tagline:'Track referrals and patient acquisition in one pipeline.', h1:'A CRM built for referrals and patient acquisition', intro:'Track referral sources, follow up on leads, and see which channels actually bring in new patients.', mockup:'crm', features:[{title:'Referral tracking',desc:'See which providers and channels drive new patients.'},{title:'Pipeline view',desc:'Leads tracked from first contact through scheduled visit.'},{title:'Follow-up automation',desc:'Automated reminders so leads don\'t go cold.'}], faq:[{q:'Does this replace our marketing tools?',a:'It\'s built specifically for healthcare referral and patient-acquisition tracking, and can complement existing marketing tools.'},{q:'Can it connect to our scheduling system?',a:'Yes, qualified leads can be handed off directly into PMS scheduling.'}]},
];
export const INDUSTRIES: Industry[] = [
  {slug:'primary-care', name:'Primary Care', path:'/industries/primary-care', summary:'High-volume visit coding and preventive care billing done right.', challenges:['High claim volume with tight margins','Preventive vs. problem-based visit coding confusion','Referral tracking across specialists'], solutions:['Streamlined coding for E/M and preventive visits','Denial monitoring tuned to primary care payer mix','Referral tracking via our Healthcare CRM']},
  {slug:'cardiology', name:'Cardiology', path:'/industries/cardiology', summary:'Complex procedure coding and prior auth for cardiac services.', challenges:['Bundled procedure coding complexity','Frequent prior authorization requirements','Device and diagnostic billing rules'], solutions:['Coders experienced in cardiology CPT bundling','Proactive prior auth workflows for cardiac procedures','Denial tracking tuned to cardiology payer patterns']},
  {slug:'orthopedics', name:'Orthopedics', path:'/industries/orthopedics', summary:'Surgical package billing and DME coordination.', challenges:['Global surgical package rules','DME and orthotics billing coordination','High-dollar claim scrutiny from payers'], solutions:['Accurate global period tracking','Coordinated DME billing workflows','Appeals support for high-dollar denials']},
  {slug:'behavioral-health', name:'Behavioral & Mental Health', path:'/industries/behavioral-health', summary:'Session-based billing and payer authorization limits.', challenges:['Authorization limits on session counts','Telehealth billing rule variability','Frequent documentation-related denials'], solutions:['Authorization tracking against session limits','Telehealth-aware billing rules by payer','Documentation review before claim submission']},
  {slug:'hospitals', name:'Hospitals & Health Systems', path:'/industries/hospitals', summary:'Institutional claims at scale with multi-department coordination.', challenges:['High-volume institutional claims (UB-04)','Multi-department coordination','Complex payer contract terms'], solutions:['Dedicated institutional claims workflows','Enterprise reporting across departments','Contract-aware payment posting and variance checks']},
  {slug:'multi-specialty', name:'Multi-Specialty Groups', path:'/industries/multi-specialty', summary:'Consistent billing standards across varied specialties.', challenges:['Inconsistent coding standards across providers','Cross-specialty reporting needs','Credentialing across multiple specialties'], solutions:['Standardized coding review across all specialties','Consolidated group-wide reporting','Centralized credentialing management']},
  {slug:'emergency-medicine', name:'Emergency Medicine', path:'/industries/emergency-medicine', summary:'High-acuity coding and rapid claims turnaround.', challenges:['Acuity-level coding disputes','High claim volume with tight turnaround needs','Out-of-network billing complexity'], solutions:['Acuity-level coding review and documentation support','Rapid claims submission workflows','IDR support for out-of-network claims']},
  {slug:'radiology', name:'Radiology', path:'/industries/radiology', summary:'Technical and professional component billing done correctly.', challenges:['Technical vs. professional component splits','Modifier accuracy on imaging claims','Prior authorization for advanced imaging'], solutions:['Precise TC/PC component billing','Modifier review before submission','Prior auth workflows for advanced imaging']},
  {slug:'dermatology', name:'Dermatology', path:'/industries/dermatology', summary:'Procedure-heavy billing with cosmetic vs. medical distinctions.', challenges:['Cosmetic vs. medically necessary distinctions','High procedure volume per visit','Pathology billing coordination'], solutions:['Documentation support for medical necessity','Procedure-level coding accuracy checks','Coordinated pathology billing workflows']},
];
export const RESOURCES: Resource[] = [
  {slug:'reduce-denials', title:'How to Reduce Medical Billing Denials', category:'RCM Guide', excerpt:'A practical framework for finding and fixing the denial patterns costing your practice the most.', relatedSlugs:{services:['denial-management','medical-billing','revenue-cycle-management']}, body:['Denials rarely come from one cause — they come from small breakdowns across eligibility checks, coding, and claim submission that compound over time.','The highest-leverage fix is root-cause tracking: categorizing every denial by reason code and routing it back to the step that caused it, rather than just resubmitting.','Practices that pair denial tracking with proactive eligibility verification typically see the fastest reduction in preventable denials.']},
  {slug:'ehr-selection-checklist', title:'EHR Selection Checklist for Independent Practices', category:'EHR Guide', excerpt:'What to evaluate before switching electronic health record systems.', relatedSlugs:{software:['ehr']}, body:['Choosing an EHR is as much about billing connectivity as clinical documentation — a system that charts well but doesn\'t hand off cleanly to billing creates downstream denials.','Evaluate specialty-specific templates, e-prescribing support, and how easily data migrates from your current system before committing.','Ask vendors directly how documentation connects to coding and claims — that handoff is often where practices lose the most time.']},
  {slug:'days-in-ar-benchmark', title:'What\'s a Good Days-in-AR Benchmark in 2026', category:'RCM Guide', excerpt:'Benchmarks vary by specialty — here\'s how to think about your own target.', relatedSlugs:{services:['ar-management','revenue-cycle-management']}, body:['Days-in-AR benchmarks vary significantly by specialty, payer mix, and claim complexity, so a single universal target can be misleading.','Instead of chasing an industry-wide number, track your own trend over time and investigate any sustained increase immediately.','Consistent AR follow-up cadence — not just headcount — is usually the biggest lever for improving this metric.']},
  {slug:'prior-auth-bottlenecks', title:'Fixing Prior Authorization Bottlenecks', category:'Billing Guide', excerpt:'Where prior auth delays actually come from, and how to close the gap.', relatedSlugs:{services:['eligibility-verification']}, body:['Prior authorization delays are usually a timing problem: requests submitted too close to the appointment leave no room for payer turnaround.','Building auth checks into scheduling — rather than as a separate front-desk task — closes most of the gap.','Tracking auth status against session or visit limits is especially important for specialties like behavioral health.']},
  {slug:'patient-portal-adoption', title:'Boosting Patient Portal Adoption Rates', category:'Software Guide', excerpt:'Why most portals go unused, and what actually drives adoption.', relatedSlugs:{software:['patient-portal']}, body:['Low patient portal adoption is rarely a technology problem — it\'s usually a friction problem at registration and first use.','Portals that combine appointment requests, messaging, and bill pay in one simple flow see meaningfully higher repeat usage.','Front-desk staff actively directing patients to the portal at check-in tends to matter more than any single portal feature.']},
  {slug:'billing-glossary', title:'Medical Billing Glossary: 50 Terms Explained', category:'Glossary', excerpt:'Plain-language definitions for the terms you\'ll see across billing and RCM.', relatedSlugs:{services:['medical-billing']}, body:['Medical billing has its own dense vocabulary — terms like "clean claim," "days in AR," and "denial rate" get used constantly but rarely explained.','This glossary is meant as a working reference for practice staff who need quick, plain-language definitions without digging through payer manuals.','We\'ll keep expanding this list as new terms come up across billing, coding, and revenue cycle management.']},
];
